version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  vaccine:
    build: .
    restart: always
    links:
      - "db:database"
    environment:
      - PGUSER=postgres
      - PGHOST=database
      - PGPASSWORD=postgres
      - PGDATABASE=vaccine
      - PGPORT=5432
    labels:
      - traefik.enable=true
      - traefik.http.routers.vaccine.entrypoints=websecure
      - traefik.http.routers.vaccine.rule=Host(`vaccine.u18.haruulzangi.mn`)
      - traefik.http.routers.vaccine.tls=true
volumes:
  db:
    driver: local

